# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ruby:2.6.5

clone:
  depth: full
pipelines:
  branches:
    dev:
      - step:
          name: Deploy dev branch to staging server
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/ffi-stage.git dev:master 
    master:
      - step:
          name: Deploy master branch to production server
          deployment: production
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/ffi-prod.git master

definitions:
  caches:
    bundler: ./vendor
